//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
<<<<<<< HEAD
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSTaskTracker.Projects.Assignments {
    
    
    public partial class AssignmentDetails {
        
        /// <summary>
        /// assignmentDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FormView assignmentDetail;
=======
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSTaskTracker.Projects.Assignments
{


    public partial class AssignmentDetails
    {
>>>>>>> 10dac3dd1b4789e8141fdb58353ede7de36e1cb6
    }
}
